import * as React from 'react';
import Head from 'next/head';
import cs from 'classnames';

import { withViewer } from '../../components/Viewer';

import styles from './new-york-times-vaccine-voting.module.css';

const NYTVaccineVoting: React.FC = () => {
  return (
    <>
      <Head>
        <title>
          reviz: NYT — Least Vaccinated U.S. Counties Have Something in Common:
          Trump Voters
        </title>
      </Head>
      <svg
        className={cs(
          styles['layer'],
          styles['svelte-jdsvwm'],
          'block h-auto max-w-full'
        )}
        viewBox="0 0 346 430"
      >
        <g>
          <line
            className={cs(styles['g-tick'], styles['svelte-jdsvwm'])}
            y1="428"
            y2="428"
            x1="5"
            x2="345"
          ></line>
          <line
            className={cs(styles['g-tick'], styles['svelte-jdsvwm'])}
            y1="235.71428571428572"
            y2="235.71428571428572"
            x1="5"
            x2="345"
          ></line>
          <line
            className={cs(styles['g-tick'], styles['svelte-jdsvwm'])}
            y1="21.428571428571452"
            y2="21.428571428571452"
            x1="5"
            x2="345"
          ></line>
          <line
            className={cs(styles['g-tick'], styles['svelte-jdsvwm'])}
            x1="0.6900000000000006"
            x2="0.6900000000000006"
            y1="21.428571428571452"
            y2="428"
          ></line>
          <line
            className={cs(styles['g-tick'], styles['svelte-jdsvwm'])}
            x1="172.5"
            x2="172.5"
            y1="21.428571428571452"
            y2="428"
          ></line>
          <line
            className={cs(styles['g-tick'], styles['svelte-jdsvwm'])}
            x1="345"
            x2="345"
            y1="21.428571428571452"
            y2="428"
          ></line>
          <circle
            cx="256"
            cy="349"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="256"
            y="369"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Ala.
          </text>
          <circle
            cx="192"
            cy="248"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="166"
            cy="276"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="258"
            cy="317"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="258"
            y="307"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Ark.
          </text>
          <circle
            cx="64"
            cy="227"
            r="7"
            fill="#709DDE"
            fillOpacity=".8"
            stroke="#709DDE"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="64"
            y="217"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Calif.
          </text>
          <circle
            cx="117"
            cy="234"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="98"
            cy="167"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="98"
            y="157"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Conn.
          </text>
          <circle
            cx="102"
            cy="237"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="181"
            cy="277"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="167"
            cy="328"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="167"
            y="348"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Ga.
          </text>
          <circle
            cx="64"
            cy="255"
            r="7"
            fill="#709DDE"
            fillOpacity=".8"
            stroke="#709DDE"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="64"
            y="275"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Hawaii
          </text>
          <circle
            cx="268"
            cy="330"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="107"
            cy="238"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="221"
            cy="323"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="194"
            cy="242"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="215"
            cy="249"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="256"
            cy="262"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="256"
            y="252"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Ky.
          </text>
          <circle
            cx="231"
            cy="339"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="133"
            cy="163"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="133"
            y="153"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Maine
          </text>
          <circle
            cx="49"
            cy="227"
            r="7"
            fill="#709DDE"
            fillOpacity=".8"
            stroke="#709DDE"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="49"
            y="247"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Md.
          </text>
          <circle
            cx="49"
            cy="169"
            r="7"
            fill="#709DDE"
            fillOpacity=".8"
            stroke="#709DDE"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="49"
            y="159"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Mass.
          </text>
          <circle
            cx="158"
            cy="271"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="158"
            y="261"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Mich.
          </text>
          <circle
            cx="140"
            cy="230"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="225"
            cy="358"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="225"
            y="378"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Miss.
          </text>
          <circle
            cx="219"
            cy="315"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="220"
            cy="266"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="229"
            cy="242"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="229"
            y="232"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Neb.
          </text>
          <circle
            cx="156"
            cy="289"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="156"
            y="309"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Nev.
          </text>
          <circle
            cx="141"
            cy="62"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="141"
            y="82"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            N.H.
          </text>
          <circle
            cx="112"
            cy="191"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="112"
            y="211"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            N.J.
          </text>
          <circle
            cx="128"
            cy="172"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="128"
            y="192"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            N.M.
          </text>
          <circle
            cx="88"
            cy="225"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="88"
            y="245"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            N.Y.
          </text>
          <circle
            cx="172"
            cy="289"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="277"
            cy="266"
            r="7"
            fill="#C23734"
            fillOpacity=".8"
            stroke="#C23734"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="195"
            cy="273"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="195"
            y="293"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Ohio
          </text>
          <circle
            cx="279"
            cy="277"
            r="7"
            fill="#C23734"
            fillOpacity=".8"
            stroke="#C23734"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="279"
            y="297"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Okla.
          </text>
          <circle
            cx="106"
            cy="268"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="106"
            y="288"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Ore.
          </text>
          <circle
            cx="164"
            cy="222"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="164"
            y="212"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Pa.
          </text>
          <circle
            cx="95"
            cy="206"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="208"
            cy="307"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="254"
            cy="215"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="254"
            y="235"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            S.D.
          </text>
          <circle
            cx="246"
            cy="333"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="187"
            cy="302"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="187"
            y="322"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Texas
          </text>
          <circle
            cx="229"
            cy="297"
            r="7"
            fill="#C67371"
            fillOpacity=".8"
            stroke="#C67371"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="229"
            y="287"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Utah
          </text>
          <circle
            cx="39"
            cy="186"
            r="7"
            fill="#709DDE"
            fillOpacity=".8"
            stroke="#709DDE"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="39"
            y="206"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Vt.
          </text>
          <circle
            cx="131"
            cy="232"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="131"
            y="252"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Va.
          </text>
          <circle
            cx="95"
            cy="251"
            r="7"
            fill="#A7B9D3"
            fillOpacity=".8"
            stroke="#A7B9D3"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="301"
            cy="299"
            r="7"
            fill="#C23734"
            fillOpacity=".8"
            stroke="#C23734"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="301"
            y="319"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            W.Va.
          </text>
          <circle
            cx="164"
            cy="230"
            r="7"
            fill="#ccc"
            fillOpacity=".8"
            stroke="#ccc"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <circle
            cx="310"
            cy="324"
            r="7"
            fill="#C23734"
            fillOpacity=".8"
            stroke="#C23734"
            strokeWidth="1"
            className={styles['svelte-jdsvwm']}
          ></circle>
          <text
            x="310"
            y="344"
            className={cs(styles['state_label'], styles['svelte-jdsvwm'])}
            textAnchor="middle"
          >
            Wyo.
          </text>
        </g>
      </svg>
    </>
  );
};

export default withViewer(NYTVaccineVoting, {
  data: {},
  href: 'https://www.nytimes.com/interactive/2021/04/17/us/vaccine-hesitancy-politics.html',
  title:
    'From The New York Times — Least Vaccinated U.S. Counties Have Something in Common: Trump Voters',
});
